spring:
  datasource:
    url: jdbc:mysql://10.1.8.67:3306/event
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations:
        - file:photo/
        - classpath:/static/
        - classpath:/static/images/
        - classpath:/static/assets/
  config:
    import:
      - "classpath:mail.yml"

  jpa:
    properties:
      hibernate:
        callable: false
  #        format_sql: true
  #    show-sql: true

  security:
    user:
      name: ADMIN
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB       # Maximum size of a single file
      max-request-size: 20MB    # Maximum size of the entire request (all files combined)

server:
  port : 8080
  servlet:
    context-path: /club
    session :
      timeout : 3600s
  error:
    whitelabel:
      enabled: false

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    #    org.mybatis: DEBUG
    #    org.apache.ibatis: DEBUG
    java.sql: DEBUG
#    org:
#      thymeleaf: TRACE
#      springframework:
#        web: DEBUG



ldap:
  url : ldap://10.1.8.3:389
  domain : dat
  INITIAL_CONTEXT_FACTORY : com.sun.jndi.ldap.LdapCtxFactory
  SECURITY_AUTHENTICATION : simple
  REFERRAL : follow

filepath:
  base-route: photo
  event: eventPhoto
  signature: signature