spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tada
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:images/, classpath:/static/, classpath:/static/images
  jpa:
    properties:
      hibernate:
        callable: false
  #        format_sql: true
  #    show-sql: true

  security:
    user:
      name: ADMIN
      password: admin

  servlet:
    multipart:
      max-file-size: 10MB       # Maximum size of a single file
      max-request-size: 20MB    # Maximum size of the entire request (all files combined)

server:
  port : 8080
  servlet:
    context-path: /club
  error:
    whitelabel:
      enabled: false

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    #    org.mybatis: DEBUG
    #    org.apache.ibatis: DEBUG
    java.sql: DEBUG
#    org:
#      thymeleaf: TRACE
#      springframework:
#        web: DEBUG



ldap:
  url : ldap://10.1.8.3:389
  domain : dat
  INITIAL_CONTEXT_FACTORY : com.sun.jndi.ldap.LdapCtxFactory
  SECURITY_AUTHENTICATION : simple
  REFERRAL : follow



