name: Deploy WAR to Windows Server

#  Trigger section
on:
  push:
    branches:
      - main

#  Build environment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Copy WAR to Windows Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: myserver.example.com
          username: Admin
          password: admin
          source: "target/*.war"
          target: C:\deploy

      - name: Deploy WAR on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: myserver.example.com
          username: Admin
          password: admin
          script: |
            powershell C:\deploy\deploy.ps1
